### ISSUE TITLE
License 문의

### ISSUE THREAD

**Issue by seungwonpark** [Qwaz/resume#1]
안녕하세요. 여기에 여쭤보는게 맞을지 모르겠지만, [Qwaz님 블로그 글](https://blog.qwaz.io/dev-diary/%EC%9B%B9-%EA%B8%B0%EB%B0%98-%EB%A0%88%EC%A3%BC%EB%A9%94-%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81%ED%95%98%EA%B8%B0)을 보고 문의드립니다.

Qwaz님께서 직접 만들어 쓰고 계신 웹 기반 레주메 템플릿이 정말 마음에 들어서 그러는데, 이것을 제가 사용해도 될까요? (레주메는 개인의 개성이 나타나기도 하는 것이기 때문에, 템플릿을 그대로 가져다 써도 되냐는 것이 조금 어려운 부탁일지도 모르겠습니다...)
만약 가능하다면, 오픈소스 라이센스를 비롯하여, 사용 조건을 정해 주시면 정말 감사하겠습니다.

**Comment by qwaz** [comment]
아쉽게도 아직 템플릿을 따로 배포할 계획은 없습니다. 추후 배포하기로 결정한다면 배포 방식과 라이센스 등을 고민할 시간이 필요할 것 같고, 현 상황에서는 사용 허가를 드리기 어려울 것 같습니다.

**Comment by seungwonpark** [comment]
아쉽지만 어쩔 수 없군요. 알겠습니다. 답변해주셔서 감사합니다!
